spring:
  #开发环境配置
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/fileinputdb?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  mvc:
    view:
      prefix: /templates
server:
  tomcat:
    uri-encoding: UTF-8
  port: 80
uploader:
  #开发环境配置   E:\software\ftpserver\file-transform-temp\ffmpeg
  #basePath: C\:/tourism/tourismfileService/
  basePath: E\:\\software\\ftpserver\\tourismfileService/
  ffmpegpath: E:\\software\\ftpserver\\file-transform-temp\\ffmpeg\\ffmpeg.exe
  mencoderpath: E:\\software\\ftpserver\\file-transform-temp\\ffmpeg\\mencoder.exe
  avifilepath: E:\\software\\ftpserver\\file-transform-temp\\ffmpeg\\temp.avi
  displayPath: ${localaddress}:${server.port}/image/
  converMp4: true
  converType: asx,asf,mpg,wmv,3gp,mov,avi,wmv9,rm,rmvb
  tempPath: E:\\software\\ftpserver
  ftpserver:
    port: 2121
    name: admin
    password: admin
    #homeDirectory: C:\\tourism\\tourismfileService
    ##开发环境配置
    homeDirectory: E:\\software\\ftpserver
    path: ftp://admin:admin@localhost:2121/
beetl:
  resource-auto-check: true       #热加载beetl模板，开发时候用
  delimiter-statement-start: \@
  delimiter-statement-end:
beetlsql:
  enabled: false

accessurl: http://localhost:8080,http://localhost:80,http://39.97.230.101:18080
localaddress: http://localhost
#localaddress: http://localhost
codelist: 123456

